### ISSUE TITLE
[BUG] Group Members receive Post Notifications even when Groups Notifications are overridden and disabled.

### ISSUE THREAD

**Issue by TodorBachvarov** [rokwire/notifications-building-block#181]
Origin: https://github.com/rokwire/illinois-app/issues/4323

Reproducible on Dev.
Steps to reproduce: 
Open Group Details -> go to Notification Preferences -> Override Notifications set to ON -> Post, Events, membership and Polls set to OFF. 

Even when the notifications are disabled on Group level, the user still receives a Notification when member creates a Post.

**Comment by mdryankov** [comment]
This is a notifications bb issue as root cause
